# Generated by Django 4.1 on 2022-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('language', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
