# Generated by Django 4.1 on 2022-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocountries',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
