# Generated by Django 4.1 on 2022-08-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_countries', '0002_alter_infocountries_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocountries',
            options={'verbose_name': 'InfoCountry', 'verbose_name_plural': 'InfoCountries'},
        ),
        migrations.RenameField(
            model_name='infocountries',
            old_name='language',
            new_name='_language',
        ),
        migrations.RenameField(
            model_name='infocountries',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='infocountries',
            old_name='region',
            new_name='_region',
        ),
        migrations.RenameField(
            model_name='infocountries',
            old_name='time',
            new_name='_time',
        ),
    ]
