# Generated by Django 4.1 on 2022-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_countries', '0003_alter_infocountries_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RemoveField(
            model_name='infocountries',
            name='_language',
        ),
    ]
