# Generated by Django 4.1 on 2022-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_countries', '0005_languagecountry_delete_infocountries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='time',
            field=models.CharField(max_length=70),
        ),
    ]
